Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 256
  Enabled: false

inherit_from: .rubocop_todo.yml

